### ISSUE TITLE
how to use on testnet?

### ISSUE THREAD

**Issue by wolverineks** [cardano-foundation/ledgerjs-hw-app-cardano#31]
**Description:**
`adaApp.signTransaction` on testnet throws error
`Action rejected by Ledger's security policy`

**Expected behavior:**
sign/submit transaction

**Actual behavior:**
throws error
`Action rejected by Ledger's security policy`

**Context:**
device: google pixel 6
OS: android 12
connectiont: BLE

this appears to be the desired behavior
if so, are there plans to enable testing on testnet?
https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/blob/2b049051ffd4193ac6c713e9bfd19521ddf45525/test/integration/__fixtures__/signTxRejects.ts#L111

**Comment by gabrielKerekes** [comment]
👋 Ledger does support testnet transactions. The test-case you're referring to tests a combination of Mainnet `networkId` and testnet `protocolMagic` which is invalid.

Could you maybe provide more information about the transaction you are trying to sign please? Also what app you are using to generate the transaction?

One reason the transaction could be failing is that the app you're signing with is not configured for testnet or that the address you're trying to transfer funds to is not a testnet address - testnet addresses are different from mainnet addresses.

**Comment by wolverineks** [comment]
its a regular old send transaction, from a testnet wallet to itself
ledger displays a test address when prompting confirmation

yoroi-mobile

what do you mean the app is not configured for testnet?

it looks like there are 37 different reasons to reject with `LEDGER_POLICY`
any way to get more details on which reason is rejecting?

**Comment by gabrielKerekes** [comment]
> what do you mean the app is not configured for testnet?

I meant that if there is a toggle in yoroi-mobile to use testnet, but apparently since you mention a testnet wallet and Ledger displaying an address then this should not be why the transaction is rejected.

> any way to get more details on which reason is rejecting?

I don't know, but perhaps @janmazak might have suggestions here. At which stage does the signing fail? What screens are shown on the Ledger screen until it fails? Do the UTxOs contain tokens? If so, they might not be [ordered canonically](https://cips.cardano.org/cips/cip21/) but I would expect yoroi to work properly in this regard and if not, there would/should be more user reports.
