### ISSUE TITLE
[BUG] Outputless transaction causes error

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/ledgerjs-hw-app-cardano#32]
**Actual behavior**
If there is a transaction without outputs, app still tries to "parse" it and trows "OUTPUTS_NOT_ARRAY" error.

**Expected behavior**
App should ignore it.

**How did you get an outputless tx???!?!?!**
1) Account has 2 utxo: 2ada and 1ada;
2) Trying to delegate it;
3) 2ada utxo acts as a deposit, 1ada utxo  acts as fee, because you can't use only 0.18ada and send 0.82ada back when the min utxo equals 0.96ada;
4) So tx contains: 2 inputs, 2 certs, fee and no outputs 

P.S. Yes, I can pass an empty array, but would be better if library can handle it by itself :)

**Comment by janmazak** [comment]
The transaction format is given by 
```
export type Transaction = {
    ...
    /**
     * Transaction outputs
     */
    outputs: Array<TxOutput>;
    ...
}
```
in `public.ts` and is based on required elements in the [CDDL](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl). This is definitely not a bug.

While ledgerjs can try and guess what the intent is if some required elements are missing, I'd say that a likely cause of missing required elements is an omission/bug in the code integrating the ledgerjs lib (and it should be easily caught by Typescript for those that are using it instead of plain js) --- transactions without outputs are rare (I think).

Also, we are trying to be consistent --- so making such a change for outputs probably means changes of similar nature elsewhere. We might change it one day, but it's not a high priority.

**Comment by janmazak** [comment]
The new Conway CDDL is even more strict, e.g. empty maps for withdrawals are not allowed etc. (not sure if the additional restrictions are enforced by nodes, but might be in the future).

**Comment by Fell-x27** [comment]
But outputs are not a required part of the transaction. There are many mandatory parts we can omit and JS-app doesn't treat it as an error. So, there is some inconsistency.
