### ISSUE TITLE
Raise minimum version recommended

### ISSUE THREAD

**Issue by henri-ly** [cardano-foundation/ledgerjs-hw-app-cardano#33]
Hello, 

we are having an issue with a new version of the cardano app that's currently on our staging env.

```
DeviceVersionUnsupported: Device app version 6.0.1 unsupported, recommended version is 5.0.
```

https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/blob/49e66c11e15830e9112e5ba1d63b73af748f4d88/src/interactions/getVersion.ts

Is it possible to change the maxMajor ? 
also is there a way for not depending on recommended version for the future or all version can bring some major breaking change on this package ? 

Thank you !

**Comment by janmazak** [comment]
@henrily-ledger We will soon release ledgerjs 6.0.0, you can get a pre-release here:
https://github.com/vacuumlabs/ledgerjs-cardano-shelley/releases/tag/v6.0.0-rc2
All sw wallets are supposed to upgrade the lib because of that compatibility check... The only breaking changes this time affect catalyst / governance voting registration, though.

The breaking changes are typically not major, i.e. they affect only a small subset of Cardano transactions, but it's hard to avoid them since at the beginning, we could not foresee them, and so the API can't be easily modified to encompass new additions to Cardano tx format. AFAIK there are no changes breaking compatibility in the coming months for Cardano tx format.

It would be possible to remove the `isLedgerAppVersionAtMost` check from `getCompatibility`, but we still don't know what changes will come in the future, and breaking changes could result in data mismatch with unpredictable consequences (the most likely outcome by far is just some error, but this is about serious money, and in case of a bug the results could be disastrous, so the compatibility check is there to prevent that).

**Comment by henri-ly** [comment]
Hello @janmazak thank you for your answer.

We will look forward for the update then :)
I understand that it's better to have control on this and avoid user to lose money so that sounds good to me.
We have just a lot of constrain on our side when it come to user that do not update their Ledger-Live client and getting stuck if they update the app version, but we will try to suggest them to update live version and so hw-app package.

Thank you again 👍
